In [1]:
# Create the input matrix 
import numpy as np
input = np.array([[2.5 ,2.4, 3.0],[0.5, 0.7, 0.2]])

In [3]:
# Show the input matrix
input

array([[2.5, 2.4, 3. ],
       [0.5, 0.7, 0.2]])

In [4]:
# Show the input matrix shape
input.shape

(2, 3)

In [5]:
# Prepare the input for calculating the correlation matrix 
data = np.array([input[:,0],input[:, 1],input[:, 2]])

In [6]:
data

array([[2.5, 0.5],
       [2.4, 0.7],
       [3. , 0.2]])

In [7]:
# Calucalte the correlation matrix
cov = np.cov(data) 
print(cov) 

[[2.    1.7   2.8  ]
 [1.7   1.445 2.38 ]
 [2.8   2.38  3.92 ]]


In [8]:
# Calculate the eigen values and eigen vectors 
from numpy import linalg as LA 
w, v = LA.eig(cov) 
print("Eigen Value") 
print(w) 
print("Eigen Vector") 
print(v)

Eigen Value
[ 7.36500000e+00  4.53352650e-16 -4.56397627e-16]
Eigen Vector
[[ 0.52110906 -0.72674907  0.27595135]
 [ 0.4429427  -0.21792415 -0.89631661]
 [ 0.72955268  0.65141757  0.34708412]]


In [27]:
# Select the vectors with highest eigen value 
eigen_vectors_max_values=np.concatenate([[v[0]], [v[2]]])

In [29]:
eigen_vectors_max_values

array([[ 0.52110906, -0.72674907,  0.27595135],
       [ 0.72955268,  0.65141757,  0.34708412]])

In [30]:
# Transpose the eigen vectors for multiplication
trans_v=eigen_vectors_max_values.transpose()

In [31]:
trans_v

array([[ 0.52110906,  0.72955268],
       [-0.72674907,  0.65141757],
       [ 0.27595135,  0.34708412]])

In [32]:
# Multiply the input and transposed eigen vectors
transformed_input=np.dot(input, trans_v)

In [33]:
transformed_input

array([[ 0.38642893,  4.42853623],
       [-0.19297955,  0.89018546]])